title: Code Space
email: frederik.debleser@kdg.be
description: >- # this means to ignore newlines until "baseurl:"
  Digitale Werkplaats van Sint Lucas Antwerpen voor studenten
  met vragen over technologie, het web, video, audio en digitale fabricatie.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.codestudio.be/" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  workshops:
    output: true
    permalink: /:collection/:name
    sort_by: workshop_date

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
